generate:

  templateRoot: ./

  destinationRoot: ./dist

  include:
  - .*
  - .config/*
  - .config/*/*
  - .config/*/*/*

  exclude:
  - .gitignore
  - .yconfig.yaml

  link: true

  delay: 0

scripts:
  - cmd: bash
    args: -cl

packageManagers:
  - os: linux
    script: sudo apt get install -y
  - os: darwin
    script: brew install

setup:
  - name: neofetch
    packages: neofetch

  - name: Oh My Zsh
    type: script
    entries:
      - script: |-
          curl -L \
            https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh \
            --output install-zsh.sh \
          && chmod +x install-zsh.sh \
          && ./install-zsh.sh \
            --unattended \
            --keep-zshrc \
          && rm install-zsh.sh
      - tags: work!
        script: |-
          curl -L \
            $(fwdproxy-config curl) \
            https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh \
            --output install-zsh.sh \
          && chmod +x install-zsh.sh \
          && ./install-zsh.sh \
            --unattended \
            --keep-zshrc \
          && rm install-zsh.sh

  - name: Powerlevel10k
    tags: work
    repo: romkatv/powerlevel10k
    dest: ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

  - name: zsh-autosuggestions
    tags: work
    repo: zsh-users/zsh-autosuggestions
    dest: ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

  - name: work fzf
    tags: work!
    script: chmod +x $HOME/.fzf/bin/fzf

  - name: tmux tpm
    tags: work
    repo: tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

  - name: neovim packer install
    tags: [nvim, work]
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim

  - name: neovim packer sync
    tags: [nvim, work, sync]
    script: |-
        nvim --headless -c "autocmd User PackerComplete quitall" -c "PackerSync"

  - name: neovim work
    tags: [nvim, work!]
    script: |-
      nvim --headless -c "SyncMetaLS" -c "quitall" \

  - name: neovim treesitter
    tags: [nvim, work]
    script: |-
      nvim --headless -c "TSInstallSync all" -c "quitall" \
      && nvim --headless -c "TSUpdateSync" -c "quitall"

  - name: go versioner
    tag: go
    script: go install github.com/yo3jones/versioner

install:

## for work
# curl $(fwdproxy-config curl) -sSL https://raw.githubusercontent.com/alacritty/alacritty/master/extra/alacritty.info | tic -x -


  groups:

    # Opener
    # https://github.com/superbrothers/opener
    
    - name: deps
      commands:
        - os: linux
          command: |-
            sudo apt update \
            && sudo apt install -y \
              git \
              vim \
              fzf \
              ripgrep \
              zsh \
              curl \
              wget \
              bat \
              tmux \
              cmake \
              automake \
              libtool \
              ninja-build \
              gettext \
              libtool-bin \
              autoconf \
              g++ \
              pkg-config \
              unzip \
              doxygen
# To install useful keybindings and fuzzy completion:
#   /Users/cpj/.brew/opt/fzf/install
        - os: darwin
          command: |-
            brew install \
              git \
              vim \
              fzf \
              ripgrep \
              zsh \
              curl \
              wget \
              bat \
              tmux
        - |-
          sh -c \
            "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        - |-
          git clone --depth=1 \
            https://github.com/romkatv/powerlevel10k.git \
            ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
        - os: darwin
          command: defaults write -g InitialKeyRepeat -int 10
        - os: darwin
          command: defaults write -g KeyRepeat -int 1 
        - git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
        - |- 
          git clone \
            https://github.com/zsh-users/zsh-autosuggestions \
            ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

    - name: gh
      commands:
        - os: linux
          arch: amd64
          command: |-
            curl \
              -fL \
              https://github.com/cli/cli/releases/download/v2.12.1/gh_2.12.1_linux_amd64.deb \
              --output gh_2.12.1_linux_amd64.deb \
            && sudo apt install -y ./gh_2.12.1_linux_amd64.deb

    - name: go
      commands:
        - os: darwin
          arch: arm64
          command: |-
            wget https://go.dev/dl/go1.18.3.darwin-arm64.pkg \
            && open go1.18.3.darwin-arm64.pkg

    - name: go-after
      commands:
        - go install mvdan.cc/gofumpt@latest
        - go install github.com/segmentio/golines@latest
        - go install golang.org/x/tools/cmd/goimports@latest
        - go install github.com/nametake/golangci-lint-langserver@latest
        - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    - name: lazygit
      commands:
        - os: linux
          command: go install github.com/jesseduffield/lazygit@latest
        - os: darwin
          command: brew install jesseduffield/lazygit/lazygit

    - name: nvim
      commands:
        - os: darwin
          command: brew install neovim
        - os: linux
          command: |-
            git clone https://github.com/neovim/neovim \
            && cd neovim \
            && git checkout stable \
            && make \
            && sudo make install \
            && cd .. \
            && rm -rf neovim
        - |-
          rm -rf ~/.local/share/nvim/site/pack/packer/start/packer.nvim \
          ; git clone --depth 1 https://github.com/wbthomason/packer.nvim \
           ~/.local/share/nvim/site/pack/packer/start/packer.nvim
        - nvim --headless -c "autocmd User PackerComplete quitall" -c "PackerSync"
        - nvim --headless -c "TSInstallSync all" -c "quitall"
        - nvim --headless -c "TSUpdateSync" -c "quitall"

#    - name: key-repeat

