#!/bin/bash

sudo apt update \
&& sudo apt install -y \
  git \
  vim \
  fzf \
  ripgrep \
  zsh \
  curl \
  wget \
  tmux \
  cmake \
  automake \
  libtool \
  ninja-build \
  gettext \
  libtool-bin \
  autoconf \
  g++ \
  pkg-config \
  unzip \
  doxygen
