#!/bin/bash

version="go1.18.2.linux-arm64.tar.gz"

wget https://go.dev/dl/$version \
&& sudo rm -rf /usr/local/go \
&& sudo tar -C /usr/local -xzf $version \
&& rm $version \
&& go install golang.org/x/tools/gopls@latest

curl \
  -sSfL \
  https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
| sh -s -- -b $(go env GOPATH)/bin v1.46.2

go install github.com/segmentio/golines@latest

go install golang.org/x/tools/cmd/goimports@latest
