#!/bin/bash

git clone https://github.com/neovim/neovim \
&& cd neovim \
&& git checkout stable \
&& make \
&& sudo make install

git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim
